### ISSUE TITLE
Set up test coverage tracking

### ISSUE THREAD

**Issue by milanmlft** [UCLH-Foundry/PIXL#369]
### Definition of Done / Acceptance Criteria

- [ ] We have a system to track test coverage
- [ ] Test coverage is checked in CI runs on `main` and Pull Requests
- [ ] require changes to increase coverage or stay the same

Part of #331 

### Details and Comments

Suggestion: use [`codecov`](https://docs.codecov.com/docs/quick-start)?
