### ISSUE TITLE
Improve the experience of using the PIXL cli

### ISSUE THREAD

**Issue by stefpiatek** [UCLH-Foundry/PIXL#399]
### Definition of Done / Acceptance Criteria

As someone running the PIXL CLI, I want to reduce the amount of manual work I'm doing to process a run quickly

- [ ] UCLH-Foundry/PIXL#396
- [ ] UCLH-Foundry/PIXL#392
- [ ] UCLH-Foundry/PIXL#393
- [ ] UCLH-Foundry/PIXL#394
- [ ] UCLH-Foundry/PIXL#397
